[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xe5c07b"

[colors.normal]
black = "0x1c252c"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.primary]
background = "0x0e1419"
foreground = "0xeaeaea"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
